# Generated by Django 3.1.7 on 2021-03-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fileing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=100)),
                ('cAddress', models.CharField(max_length=200)),
                ('cRoad_Block_Sector', models.CharField(max_length=200)),
                ('cCity_Village_House', models.CharField(max_length=200)),
                ('cPost_Office', models.CharField(max_length=100)),
                ('cPostal_Code', models.CharField(max_length=100)),
                ('cDistrict', models.CharField(max_length=100)),
                ('cPolice_Station', models.CharField(max_length=100)),
                ('cCountry', models.CharField(max_length=100)),
                ('Choose_Crime', models.CharField(max_length=100)),
                ('Time', models.CharField(max_length=100)),
                ('Crime_Descrip', models.TextField()),
                ('sName', models.CharField(max_length=100)),
                ('sAddress', models.CharField(max_length=100)),
                ('sRoad_Block_Sector', models.CharField(max_length=100)),
                ('sCity_Village_House', models.CharField(max_length=100)),
                ('sPost_Office', models.CharField(max_length=100)),
                ('sPostal_Code', models.CharField(max_length=100)),
                ('sDistrict', models.CharField(max_length=100)),
                ('sPolice_Station', models.CharField(max_length=100)),
                ('sCountry', models.CharField(max_length=100)),
            ],
        ),
    ]
