# Generated by Django 3.1.7 on 2021-03-08 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0002_remove_fileing_caddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileing',
            name='sAddress',
        ),
    ]
